version: '3.1'

services:
   
  database:
    image: postgres
    restart: always
    tty: true
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: example
      POSTGRES_DB: docker
    ports:
      - 8081:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
