version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: example
      POSTGRES_DB: docker

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
