version: '3.1'

services:
  golang:
    image: golang:1.16.5-alpine3.14
    working_dir: /go/src
    volumes:
      - ./app/:/go/src
    tty: true
    ports:
      - 8080:8080
    networks:
      - app-network
    links:
      - database

  database:
    image: postgres
    restart: always
    tty: true
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: example
      POSTGRES_DB: test_docker
    ports:
      - 8081:5432
    networks:
      - app-network

  database_mysql:
    image: mysql:5.7
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test_docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: example
    ports:
      - 8082:3306
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
