version: "3.2"
services:
  sql-server-db:
    container_name: sql-server-db
    image: datagrip/mssql-server-linux
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "docker"
      ACCEPT_EULA: "Y"
    volumes:
      - ./data:/var/opt/mssql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
